set(CPACK_PACKAGE_NAME ${PROJECT_NAME})
set(CPACK_PACKAGE_VERSION ${PROJECT_VERSION})
set(CPACK_PACKAGE_ICON "${CMAKE_SOURCE_DIR}/data/img/icon\\\\icon.ico")
# set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_SOURCE_DIR}/LICENSE.txt")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README.md")
set(CPACK_PACKAGE_DESCRIPTION ${PROJECT_DESCRIPTION})
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY ${PROJECT_DESCRIPTION})
set(CPACK_PACKAGE_CONTACT "Moth <QianMoth@qq.com>")
set(CPACK_PACKAGE_VENDOR "Moth") # Company
set(CPACK_PACKAGE_HOMEPAGE_URL ${PROJECT_HOMEPAGE_URL})
# 系统信息
set(CPACK_SYSTEM_NAME "${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
string(TOLOWER ${CPACK_SYSTEM_NAME} CPACK_SYSTEM_NAME)
# 编译时间
string(TIMESTAMP COMPILE_TIME %Y%m%d_%H%M%S)
# 输出名称
set(CPACK_PACKAGE_FILE_NAME "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}-${CPACK_SYSTEM_NAME}")
# 输出目录
set(CPACK_PACKAGE_DIRECTORY ${PROJECT_BINARY_DIR}/package)

if(WIN32) # Include all dynamically linked runtime libraries such as MSVCRxxx.dll
  list(APPEND CPACK_GENERATOR "NSIS")
  set(CPACK_NSIS_MUI_ICON "${CPACK_PACKAGE_ICON}")
  set(CPACK_NSIS_MUI_UNIICON "${CPACK_PACKAGE_ICON}")
  set(CPACK_NSIS_DISPLAY_NAME "${CPACK_PACKAGE_NAME}")
  set(CPACK_NSIS_PACKAGE_NAME "${CPACK_PACKAGE_NAME}")
elseif(APPLE)
  set(CPACK_PACKAGE_ICON "${CMAKE_SOURCE_DIR}/data/img/icon/icon.icns")
  list(APPEND CPACK_GENERATOR "DragNDrop")
else()
endif()

message(STATUS "CPack generators: ${CPACK_GENERATOR}, Time: ${COMPILE_TIME}")

include(CPack)
